[package]
name = "oidc-token-test-service"
version = "0.1.0"
authors = ["Olger Warnier <olger@spectare.nl>"]
edition = "2018"

[dependencies]
actix-web = "2.0.0"
actix-rt = "1.0.0"
actix-service = "1.0.1"
biscuit = "0.4.2"
clap = "2.33.0"
num = "0.2"
bytes = "0.5.3"
chrono = "0.4.10"
der-parser = "3.0.3"
env_logger = "0.7.1"
futures = "0.3.1"
pem = "0.7.0"
ring = "0.16.9"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
nanoid = "0.2.0"
sysinfo = "0.10.4"

[profile.release]
debug = true

[patch.crates-io]
actix-http = { git = "https://github.com/actix/actix-web.git" }
