[package]
authors = ["Olger Warnier <olger@spectare.nl>"]
edition = "2021"
name = "oidc-token-test-service"
version = "0.3.0"

[dependencies]
actix-cors = "0.6.3"
actix-multipart = "0.5.0"
actix-rt = "2.8.0"
actix-service = "2.0.2"
actix-web = "4.3.0"
actix-4-jwt-auth = "1.0.0"
#actix-4-jwt-auth = { path = "../actix-4-jwt-auth" }
actix-files = "0.6.2"
biscuit = "0.6.0-beta1"
bytes = "1.3.0"
chrono = "0.4.23"
clap = {version = "4.1.4", features = ["derive", "unicode", "env"]}
der-parser = "8.1.0"
env_logger = "0.10.0"
futures = "0.3.24"
futures-core = {version = "0.3.26", default-features = false, features = ["alloc"]}
futures-util = {version = "0.3.24", default-features = false, features = ["alloc"]}
num = "0.3"
tokio = {version = "1.24.2", features = ["full"]}
nanoid = "0.4.0"
pem = "1.1.1"
ring = "0.16.9"
data-encoding = "2.3.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
sysinfo = "0.27.7"
reqwest = {version = "0.11.14", features = ["json", "blocking"]}

# [profile.release]
# debug = true

# [patch.crates-io]
# actix-http = {git = "https://github.com/actix/actix-web.git"}
