[package]
authors = ["Olger Warnier <olger@spectare.nl>"]
edition = "2018"
name = "oidc-token-test-service"
version = "0.2.0"

[dependencies]
actix-cors = "0.6.0-beta.9"
actix-multipart = "0.4.0-beta.13"
actix-rt = "2.6.0"
actix-service = "2.0.2"
actix-web = "4.0.0-rc.2"
biscuit = "0.6.0-beta1"
bytes = "1.1.0"
chrono = "0.4.10"
clap = "2.34.0"
der-parser = "6.0.1"
env_logger = "0.9.0"
futures = "0.3.19"
futures-core = {version = "0.3.19", default-features = false, features = ["alloc"]}
futures-util = {version = "0.3.19", default-features = false, features = ["alloc"]}
num = "0.3.1"
tokio = {version = "1.16.1", features = ["full"]}
# futures = "0.3.1"
nanoid = "0.4.0"
# num-bigint = "0.4.2"
# num = "0.4.0"
pem = "1.0.2"
ring = "0.16.9"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
sysinfo = "0.23.0"

# [profile.release]
# debug = true

# [patch.crates-io]
# actix-http = {git = "https://github.com/actix/actix-web.git"}
