version: 2

jobs:
  build:
    docker:
      - image: circleci/rust:1.40-buster 

    environment:
      # Set your codecov token if your repository is private.
      CODECOV_TOKEN: "ab1ebf03-ceaa-44e5-a5c3-991540225856" 
      TZ: "/usr/share/zoneinfo/Europe/Paris"

    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Check formatting
          command: |
            rustfmt --version
            cargo fmt -- 
        #- run:
        #  name: Nightly Build
        #  command: |
        #    rustup run nightly rustc --version --verbose
        #    rustup run nightly cargo --version --verbose
        #    rustup run nightly cargo build
       - run:
           name: Stable Build
           command: |
             rustup run stable cargo build
      - run:
          name: Test
          command: rustup run stable cargo test
      - run:
          name: Upload Coverage
          command: |
            .scripts/codecov.sh
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"
