version: 2.1
#orbs:
#  codecov: codecov/codecov@1.0.5
jobs:
  build:
    docker:
      - image: circleci/rust:1.40-buster 

    environment:
      # Set your codecov token if your repository is private.
      CODECOV_TOKEN: "ab1ebf03-ceaa-44e5-a5c3-991540225856" 
      TZ: "/usr/share/zoneinfo/Europe/Paris"

    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Install KCOV
          command: |
          export KCOV_VERSION=37
          wget https://github.com/SimonKagstrom/kcov/archive/v$KCOV_VERSION.tar.gz && \
              tar xzf v$KCOV_VERSION.tar.gz && \
              rm v$KCOV_VERSION.tar.gz && \
              cd kcov-$KCOV_VERSION && \
              mkdir build && cd build && \
              cmake .. && make && make install && \
              cd ../.. && rm -rf kcov-$KCOV_VERSION
      - run:
          name: Stable Build
          command: |
            cargo build
      - run:
          name: Test
          command: cargo test
      - run:
          name: Upload Coverage
          command: |
            .scripts/codecov.sh
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"
