  version: 2.1
  #orbs:
  #  codecov: codecov/codecov@1.0.5
  #docker-workflow:
  jobs:
    build:
      docker:
        - image: spectare/rust-build:latest

      environment:
        # Set your codecov token if your repository is private.
        CODECOV_TOKEN: "ab1ebf03-ceaa-44e5-a5c3-991540225856" 
        TZ: "/usr/share/zoneinfo/Europe/Paris"

      steps:
        - checkout
        - restore_cache:
            key: project-cache
        - run:
            name: Stable Build
            command: |
              cargo build
        - run:
            name: Test
            command: cargo test
        - run:
            name: Upload Coverage
            command: |
              .scripts/codecov.sh
        - save_cache:
            key: project-cache
            paths:
              - "~/.cargo"
              - "./target"
    
    publish-docker:
      machine: true
      steps:
        - checkout
        - run: 
            name: Docker build and push
            command: |
              echo `git describe --tags --exact-match` > /tmp/version.txt
              TAG=$(cat /tmp/version.txt)
              docker build \
                -t spectare/oidc-token-test-service:$TAG \
                -t spectare/oidc-token-test-service:latest \
                --build-arg VERSION=$(cat /tmp/version.txt) \
                --build-arg COMMITID=${CIRCLE_SHA1} \
                .
              echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
              docker push spectare/oidc-token-test-service:$TAG

  workflows:
    version: 2
    ci:
      jobs:
        - build
        - publish-docker:
            context: DOCKER
            requires:
              - build
            filters:
              branches:
                only: master